/**
 * lib_zk/prover.ts
 * ZK Proof generation using Noir + Barretenberg (UltraHonk)
 *
 * The Noir circuit proves: balance >= threshold
 * Inputs:
 *   - balance (private)     : u64 (cents)
 *   - threshold (public)    : u64 (cents)
 * Output: proof bytes + public inputs [threshold]
 */

export interface ProofInputs {
  balance: bigint;    // private: actual balance in cents
  threshold: bigint;  // public: minimum required balance in cents
}

export interface ZKProof {
  proof: Uint8Array;
  publicInputs: string[];   // hex strings as expected by Soroban verifier
  proofHex: string;
}

let circuitLoaded = false;
let backend: unknown = null;
let noir: unknown = null;

/**
 * Lazy-load Noir + Barretenberg WASM.
 * We dynamically import to avoid SSR issues with WASM.
 */
async function initNoir() {
  if (circuitLoaded && backend && noir) return { backend, noir };

  // Dynamically import Noir libs (WASM, must be client-side)
  const [
    { Noir },
    { UltraHonkBackend },
  ] = await Promise.all([
    import("@noir-lang/noir_js"),
    import("@noir-lang/backend_barretenberg"),
  ]);

  // Load the compiled circuit artifact (JSON produced by `nargo compile`)
  // This file is generated by the Noir compilation step.
  const circuitArtifact = await import("../circuits/target/balance_proof.json");

  const backendInstance = new UltraHonkBackend(circuitArtifact.bytecode);
  const noirInstance = new Noir(circuitArtifact as never);

  backend = backendInstance;
  noir = noirInstance;
  circuitLoaded = true;

  return { backend: backendInstance, noir: noirInstance };
}

/**
 * Generate a ZK proof that balance >= threshold.
 * Balance is kept private; threshold is the public input.
 */
export async function generateBalanceProof(
  inputs: ProofInputs
): Promise<ZKProof> {
  if (inputs.balance < 0n) throw new Error("Balance cannot be negative");
  if (inputs.threshold < 0n) throw new Error("Threshold cannot be negative");

  const { backend, noir } = await initNoir() as {
    backend: { generateProof: (w: Uint8Array) => Promise<{ proof: Uint8Array; publicInputs: string[] }> },
    noir: { execute: (i: Record<string, string>) => Promise<{ witness: Uint8Array }> }
  };

  // Execute the circuit to get the witness
  const { witness } = await noir.execute({
    balance: inputs.balance.toString(),
    threshold: inputs.threshold.toString(),
  });

  // Generate UltraHonk proof
  const { proof, publicInputs } = await backend.generateProof(witness);

  const proofHex = Buffer.from(proof).toString("hex");

  return {
    proof,
    publicInputs,  // ["0x...(threshold as felt)"]
    proofHex,
  };
}

/**
 * Verify a proof locally (client-side sanity check before on-chain submit).
 */
export async function verifyBalanceProofLocal(zkProof: ZKProof): Promise<boolean> {
  const { backend } = await initNoir() as {
    backend: { verifyProof: (p: { proof: Uint8Array; publicInputs: string[] }) => Promise<boolean> }
  };
  return backend.verifyProof({
    proof: zkProof.proof,
    publicInputs: zkProof.publicInputs,
  });
}

/** Convert threshold in USD units to cents BigInt for circuit input */
export function usdToCents(usd: number): bigint {
  return BigInt(Math.round(usd * 100));
}
